#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: missing required command: $1" >&2
    exit 1
  }
}

is_root() {
  [[ "${EUID:-$(id -u)}" -eq 0 ]]
}

prompt() {
  local var="$1"
  local label="$2"
  local def="${3:-}"
  local val=""
  if [[ -n "$def" ]]; then
    read -r -p "$label [$def]: " val || true
    val="${val:-$def}"
  else
    read -r -p "$label: " val || true
  fi
  printf -v "$var" '%s' "$val"
}

prompt_secret() {
  local var="$1"
  local label="$2"
  local val=""
  read -r -s -p "$label: " val || true
  echo
  printf -v "$var" '%s' "$val"
}

slugify() {
  # lower, replace non-alnum with underscore, collapse underscores, trim
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/_/g; s/^_+//; s/_+$//; s/_+/_/g'
}

ensure_venv_support() {
  # If python3 -m venv fails (Debian/Ubuntu missing python3-venv), install it.
  if python3 -m venv /tmp/.venv_test_$$ >/dev/null 2>&1; then
    rm -rf /tmp/.venv_test_$$
    return 0
  fi

  echo "python3 venv support missing. Installing python3-venv..."
  if ! is_root; then
    echo "ERROR: cannot install python3-venv because we are not root." >&2
    echo "Run as root, or install manually: apt install -y python3-venv" >&2
    exit 1
  fi

  apt-get update
  apt-get install -y python3-venv
}

select_db() {
  echo "Detected DB candidates:"
  local candidates=()

  if [[ -f "/root/sprout-track/db/baby-tracker.db" ]]; then
    candidates+=("/root/sprout-track/db/baby-tracker.db")
    echo "  [1] /root/sprout-track/db/baby-tracker.db"
  fi
  echo "  [0] Enter custom path"

  local choice=""
  read -r -p "Choose DB path: " choice || true
  choice="${choice:-1}"

  if [[ "$choice" == "0" ]]; then
    prompt DB_PATH "Enter DB path"
  else
    local idx=$((choice-1))
    DB_PATH="${candidates[$idx]:-}"
  fi

  if [[ -z "${DB_PATH:-}" || ! -f "$DB_PATH" ]]; then
    echo "ERROR: DB path not found: ${DB_PATH:-<empty>}" >&2
    exit 1
  fi
}

select_baby() {
  echo
  echo "Babies found in DB:"

  # We rely on sqlite3 CLI for setup-time discovery.
  local sql="SELECT id, name FROM Baby ORDER BY createdAt DESC;"
  local rows
  rows="$(sqlite3 -separator $'\t' "$DB_PATH" "$sql" 2>/dev/null || true)"

  if [[ -z "$rows" ]]; then
    echo "ERROR: Could not list babies from DB (query returned no rows)." >&2
    echo "Tried SQL: $sql" >&2
    exit 1
  fi

  mapfile -t BABY_ROWS < <(printf '%s\n' "$rows")

  local i
  for i in "${!BABY_ROWS[@]}"; do
    local id name
    id="$(printf '%s' "${BABY_ROWS[$i]}" | cut -f1)"
    name="$(printf '%s' "${BABY_ROWS[$i]}" | cut -f2)"
    echo "  [$((i+1))] $name ($id)"
  done

  local choice
  read -r -p "Choose baby: " choice
  local idx=$((choice-1))

  BABY_ID="$(printf '%s' "${BABY_ROWS[$idx]}" | cut -f1)"
  BABY_NAME="$(printf '%s' "${BABY_ROWS[$idx]}" | cut -f2)"

  if [[ -z "$BABY_ID" || -z "$BABY_NAME" ]]; then
    echo "ERROR: invalid selection." >&2
    exit 1
  fi
}

main() {
  need_cmd sqlite3
  need_cmd sed
  need_cmd tr
  need_cmd awk
  need_cmd python3

  echo "Sprout Track -> HA MQTT Exporter setup"
  echo "Project: $PROJECT_ROOT"
  echo

  echo "Environment:"
  echo "  [1] Proxmox / LXC (no sudo assumed; typically running as root)"
  echo "  [2] Bare metal / VM (sudo may be used if not root)"
  local env_choice
  read -r -p "Choose [1/2] (default 1): " env_choice || true
  env_choice="${env_choice:-1}"
  # (We don’t actually use env_choice for logic; we detect root automatically.)

  select_db
  select_baby

  echo
  prompt MQTT_HOST "MQTT host / IP"
  prompt MQTT_PORT "MQTT port" "1883"
  prompt MQTT_USER "MQTT username (leave empty if none)" ""
  prompt_secret MQTT_PASS "MQTT password (leave empty if none)"
  prompt POLL_SEC "Poll interval (seconds)" "300"

  local bn_slug
  bn_slug="$(slugify "$BABY_NAME")"
  local default_prefix="sprout_track_${bn_slug}"
  prompt HA_PREFIX "Home Assistant sensor object_id prefix" "$default_prefix"

  echo
  echo "Install options:"
  echo "  [1] Dev setup only (write config.yaml + .secrets.env in this folder)"
  echo "  [2] Install as a systemd service (copies to /opt, creates venv, enables service)"
  local install_choice
  read -r -p "Choose [1/2] (default 1): " install_choice || true
  install_choice="${install_choice:-1}"

  local INSTALL_ROOT=""
  if [[ "$install_choice" == "2" ]]; then
    if ! is_root; then
      echo "ERROR: systemd install requires root. Re-run as root (or choose option 1)." >&2
      exit 1
    fi
    prompt INSTALL_ROOT "Install directory" "/opt/sprouttrack-mqtt-exporter"
  fi

  cat > config.yaml <<CFG
# Generated by scripts/setup.sh

db_path: ${DB_PATH}
baby_id: "${BABY_ID}"
baby_name: "${BABY_NAME}"
baby_slug: "${bn_slug}"

# Used for HA entity_ids via MQTT discovery object_id:
# -> sensor.<ha_object_id_prefix>_<metric_key>
ha_object_id_prefix: "${HA_PREFIX}"

poll_sec: ${POLL_SEC}

mqtt:
  host: ${MQTT_HOST}
  port: ${MQTT_PORT}

base_topic: sprouttrack
ha_discovery_prefix: homeassistant
timezone: Europe/Berlin
CFG

  cat > .secrets.env <<SECRETS
# Generated by scripts/setup.sh
MQTT_USER=${MQTT_USER}
MQTT_PASS=${MQTT_PASS}
SECRETS

  chmod 600 .secrets.env

  if [[ "$install_choice" == "1" ]]; then
    echo
    echo "Wrote: $(pwd)/config.yaml"
    echo "Wrote: $(pwd)/.secrets.env (mode 600)"
    echo
    echo "Next (manual):"
    echo "  python3 -m venv .venv"
    echo "  source .venv/bin/activate"
    echo "  pip install -r requirements.txt"
    echo "  PYTHONPATH=\$(pwd)/src python -m sprouttrack_exporter --config config.yaml --secrets .secrets.env"
    return 0
  fi

  # Option 2: Install as systemd service
  echo
  echo "Installing to: $INSTALL_ROOT"
  mkdir -p "$INSTALL_ROOT"

  (cd "$PROJECT_ROOT" && tar --exclude='.venv' --exclude='__pycache__' --exclude='*.pyc' --exclude='.git' -cf - .) \
    | (cd "$INSTALL_ROOT" && tar -xf -)

  chmod 600 "$INSTALL_ROOT/.secrets.env" || true

  ensure_venv_support
  python3 -m venv "$INSTALL_ROOT/.venv"
  "$INSTALL_ROOT/.venv/bin/pip" install --upgrade pip
  "$INSTALL_ROOT/.venv/bin/pip" install -r "$INSTALL_ROOT/requirements.txt"

  local SERVICE_NAME="sprouttrack-mqtt-exporter.service"
  local UNIT_SRC="$INSTALL_ROOT/systemd/sprouttrack-mqtt-exporter.service.template"
  local UNIT_DST="/etc/systemd/system/$SERVICE_NAME"

  if [[ ! -f "$UNIT_SRC" ]]; then
    echo "ERROR: missing systemd unit template at $UNIT_SRC" >&2
    exit 1
  fi

  # Patch systemd unit:
  # - WorkingDirectory
  # - EnvironmentFile
  # - Ensure PYTHONPATH=<root>/src (required for src-layout)
  # - ExecStart
  awk -v root="$INSTALL_ROOT" '
    BEGIN { in_service=0; has_py=0 }

    /^\[Service\]/ {
      in_service=1
      print
      next
    }

    in_service==1 && has_py==0 && $0 ~ /^Environment=PYTHONPATH=/ {
      has_py=1
      print "Environment=PYTHONPATH=" root "/src"
      next
    }

    /^WorkingDirectory=/ {
      print "WorkingDirectory=" root
      next
    }

    /^EnvironmentFile=/ {
      print "EnvironmentFile=" root "/.secrets.env"
      next
    }

    /^ExecStart=/ {
      print "ExecStart=" root "/.venv/bin/python -m sprouttrack_exporter --config " root "/config.yaml --secrets " root "/.secrets.env"
      next
    }

    # If we are inside [Service] and we reach the first non-Environment lines,
    # inject PYTHONPATH once (if not already present).
    in_service==1 && has_py==0 && $0 !~ /^Environment(File)?=/ && $0 !~ /^WorkingDirectory=/ {
      print "Environment=PYTHONPATH=" root "/src"
      has_py=1
      print
      next
    }

    { print }
  ' "$UNIT_SRC" > "$UNIT_DST"

  systemctl daemon-reload
  systemctl enable --now "$SERVICE_NAME"

  echo
  echo "Installed and started: $SERVICE_NAME"
  echo "Check status: systemctl status $SERVICE_NAME --no-pager"
}

main "$@"
